.Dd February 03, 2023
.Dt SINCA 1
.Sh NAME
.Nm sinca
.Nd simple infinite canvas for X
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh DESCRIPTION
The
.Nm
application lets you draw over an infinite canvas using the mouse.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/sinca/issues
