.Dd February 01, 2023
.Dt XYNE 1
.Sh NAME
.Nm xyne
.Nd description
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Sh DESCRIPTION
The
.Nm
application.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl v
display the program version
.El
.Sh SEE ALSO
.Xr X 7
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xyne/issues
